spring:
  profiles:
    active: local

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  access-expiration-time: 1296000000 # 15일
  prefix: Bearer
  secret-key: ${JWT_SECRET}

kakao:
  api:
    client-key: ${KAKAO_API_KEY}
    redirect-uri: ${KAKAO_REDIRECT_URI}

apple:
  api:
    client-id: ${APPLE_API_CLIENT_ID}
    client-secret: ${APPLE_API_CLIENT_SECRET}
    redirect-uri: ${APPLE_API_REDIRECT_URI}
    team-id: ${APPLE_API_TEAM_ID}
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/letter
    driver-class-name: org.postgresql.Driver
    username: unithon
    password: unithon

debug: true
