name: Deploy to cloudtype

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: ${{ secrets.CLOUDTYPE_PROJECT }}
          stage: main
          yaml: >
            name: pro

            app: java@17

            options:
              ports: 8080
              env:
                - name: DB_NAME
                  value: ${{ secrets.DB_NAME }}
                - name: DB_USERNAME
                  value: ${{ secrets.DB_USERNAME }}
                - name: DB_HOST
                  value: ${{ secrets.DB_HOST }}
                - name: DB_PORT
                  value: ${{ secrets.DB_PORT }}
                - name: DB_PASSWORD
                  value: ${{ secrets.DB_PASSWORD }}
                - name: JWT_SECRET
                  value: ${{ secrets.JWT_SECRET }}
                - name: KAKAO_API_KEY
                  value: ${{ secrets.KAKAO_API_KEY }}
                - name: KAKAO_REDIRECT_URI
                  value: ${{ secrets.KAKAO_REDIRECT_URI }}
                - name: SPRING_PROFILES_ACTIVE
                  value: prod
                - name: TZ
                  value: Asia/Seoul
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}